name: Github-CI/CD

on:
  [push]
  
jobs:
  apiRobotTest:
    name: Robot - Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
      - name: Start test
        run: |
          python -m robot -i api test/RobotFrameWork/tc.robot
    
  postmanTest:
    name: Postman Test
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run Newman
        uses: anthonyvscode/newman-action@v1.1
        with: 
          collection: ${{ github.workspace }}/test/Postman/TestApi.json
          reporters: cli
      
  loadTest:
    name: K6
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: K6 Run
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ${{ github.workspace }}/test/k6/loadtest.js
        
